tasks:
  - name: swagger-editor
    init: |    
      npm install -g http-server
      wget https://github.com/swagger-api/swagger-editor/releases/download/v2.10.4/swagger-editor.zip
      unzip swagger-editor.zip
    command:
      http-server swagger-editor